language: smalltalk
sudo: false

os:
  - linux
  - osx

smalltalk:
  - Squeak-trunk
# Squeak 5.0 can't load Traits due to a bug in the class format definition.
# This issue has been fixed in trunk
#  - Squeak-5.0
  - Squeak-4.6
  - Squeak-4.5
  - Pharo-alpha
  - Pharo-5.0
  - Pharo-4.0

matrix:
  include:
    - smalltalk: Pharo-alpha
      smalltalk_config: .bleedingEdge.ston
      os: linux
    - smalltalk: Pharo-alpha
      smalltalk_config: .bleedingEdge.ston
      os: osx
  allow_failures:
    - smalltalk: Pharo-alpha
  fast_finish: true
